source 'http://rubygems.org'
gem 'sinatra'
gem 'sinatra-reloader'
gem 'sprockets'
gem 'kramdown'
gem 'sass'
gem 'coffee-script'
gem 'haml'
gem 'haml-coffeescript', '0.1.0'
#gem 'colorize'
#gem 'watchr'
#gem 'execjs'
#gem 'therubyracer'

gem "yui-compressor"
