dir = "../assets/javascripts"
require "#{dir}/jquery-ext"
require "#{dir}/jquery-g2d"
require "#{dir}/core"
require "#{dir}/0.1.0"
require "#{dir}/common"
require "#{dir}/usecase"
require "#{dir}/class"
require "#{dir}/sequence"
require "#{dir}/plugin"

#console.log "Loaded successfully."
